language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

script:
  - npm version patch
  - git remote get-url origin
  - git add --all; git commit user.name='liyatang' user.email='liyatang@qq.com' -m '[ci skip] test push '; git push -f 'https://${GH_TOKEN}@github.com/liyatang/demo.git' master:master
