language: node_js

node_js:
  - 'lts/*'

install:
  - npm install

script:
  - git config --global user.name "liyatang"
  - git config --global user.email "liyatang@qq.com"
  - npm version patch
  - git remote get-url origin
  - git add --all
  - git commit -m '[ci skip] test push '
  - git push -f 'https://liyatang:c12886ec5684245a65ffb9f5efb93760b4f300e3@github.com/liyatang/demo.git' master:master
