language: node_js

node_js:
  - 'lts/*'

before_install:
  - git config --global user.name 'liyatang'
  - git config --global user.email 'liyatang@guanmai.cn'

install:
  - npm install

script:
  - npm version patch
  - git add --all; git commit -m '[ci skip] test push '; git push -f 'https://${GH_TOKEN}@github.com/gmfe/react-gm.git' master:master
